services:
  postgres:
    image: postgres:16.10-alpine@sha256:7898d413578ff5fa67ce49233cc9743e282010eb2ec6ebf7834a63f4a60b05f0
    container_name: postgres_db
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_PTRACE
      - MKNOD
      - AUDIT_WRITE
      - SETFCAP
      - SYS_CHROOT
      - SETPCAP
      - NET_BIND_SERVICE
      - NET_RAW
      - SYS_MODULE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - KILL
      - LINUX_IMMUTABLE
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: its_local
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d its_local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"

volumes:
  postgres_data:
